# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title:            "Se7enTime"
description:      "Al Banna lagi nulis atau lagi copy-paste"
url:              blog.zazakhuna.com
baseurl:          "/"
paginate:         7

author:
  name:           "Al Banna"

# Custom vars
twitter:        https://twitter.com/Se7enTime
github:         https://github.com/Se7enTime
